# ParticleX Configuration
# https://github.com/argvchs/hexo-theme-particlex

# Avatar image
avatar: https://img.fastmirror.net/s/2023/10/29/653deb00353b8.png

# Home page background image
background: 
 - https://img.fastmirror.net/s/2023/07/17/64b5484cb467f.jpg

# Loading image
loading: https://www.helloimg.com/images/2023/01/23/oRbKc6.gif

# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

# Main menu navigation
menu:
    首页:
        name: house
        theme: solid
        link: /
    更新日志:
        name: box-archive
        theme: solid
        link: /archives
    下载:
        name: download
        theme: solid
        link: /download
    相关链接:
        name: book
        theme: solid
        link: /links
    留言板:
        name: comment
        theme: solid
        link: /board

# 文章目录
toc:
    enable: true

# 图片懒加载
lazyload:
    enable: true

# Side info card
card:
    enable: true
    description: |
        一个简洁全能的Minecraft开服器
        由 MCSL2 开发组 精心呈现
        
        [点击此处查看乐子！](https://mcsl.com.cn/fuckFLSQ)
    iconLinks:
        落雪无痕的GitHub:
            name: github
            theme: brands
            link: https://www.github.com/LxHTT
        开发组的GitHub:
            name: github
            theme: brands
            link: https://www.github.com/MCSLTeam
        落雪无痕的Bilibili:
            name: bilibili
            theme: brands
            link: https://space.bilibili.com/488011295
        MCSL2官方QQ群:
            name: qq
            theme: brands
            link: https://jq.qq.com/?_wv=1027&k=x2ISlviQ
        MCSL2的爱发电:
            name: coins
            theme: solid
            link: https://afdian.net/a/MCSLTeam
    friendLinks:
        维度前端: https://www.df100.ltd
        Z_Tsin: https://ztsin.cn/
        FiveCDN公益加速: https://cdn.5-5.site
        玖壹云互联: https://idc.jyywl.com/
        WB-Block: https://wb-block.top
        shenjack: http://shenjack.top:81

# Footer info
footer:
    since: 2022
    # Customize the server domain name ICP
    ICP:
        enable: true
        code: 鲁ICP备2023001164号-2
        link: https://beian.miit.gov.cn/

# Polyfill
# https://polyfill.io
polyfill:
    enable: true
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: vs
    styleDark: github-dark

# Rendering math with KaTeX
math:
    enable: false

# Darkmode
darkmode:
    enable: auto

# Image Preview
preview:
    enable: true

# Article encryption
crypto:
    enable: true

# Search
search:
    enable: true

# Giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang: zh-CN

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy
    sites: # Sites
        {}
        # www.example.com:
        #    clientID:
        #    clientSecret:

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: # Waline server address url, you should set this to your own link
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
        {zh-CN}
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
        - mail
    lang: zh-CN # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: disable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: true
    envID: https://mcsl2-comment.ymbot.top/.netlify/functions/twikoo
    region: zh-CN
    path: location.pathname
    lang: zh-CN
